source 'https://rubygems.org'

gem 'rails'
gem 'puma'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'materialize-sass'
gem 'bootstrap-sass'

group :development, :test do
  gem 'sqlite3'
  gem 'byebug',   platform: :mri
end

group :development do
  gem 'web-console'
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
end

group :test do
  gem 'rails-controller-testing'
  gem 'minitest-reporters'
  gem 'guard'
  gem 'guard-minitest'
end

group :production do
  gem 'pg'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# source 'https://rubygems.org'
#
# git_source(:github) do |repo_name|
#   repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
#   "https://github.com/#{repo_name}.git"
# end
#
# gem 'rails', '~> 5.0.1'
# gem 'sqlite3'
# gem 'puma', '~> 3.0'
# gem 'sass-rails', '~> 5.0'
# gem 'uglifier', '>= 1.3.0'
# gem 'coffee-rails', '~> 4.2'
# gem 'jquery-rails'
# gem 'turbolinks', '~> 5'
# gem 'jbuilder', '~> 2.5'
#
# group :development, :test do
#   gem 'byebug', platform: :mri
# end
#
# group :development do
#   gem 'web-console', '>= 3.3.0'
#   gem 'listen', '~> 3.0.5'
#   gem 'spring'
#   gem 'spring-watcher-listen', '~> 2.0.0'
# end
#
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
